[workspace]
resolver = "2"
members = ["chton", "benches"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
tagma-core = { git = "https://github.com/ssccsorg/syntagma", branch = "181-tagma-geo-nostd" }
tagma-geo = { git = "https://github.com/ssccsorg/syntagma", branch = "181-tagma-geo-nostd" }
tagma-map = { git = "https://github.com/ssccsorg/syntagma", branch = "181-tagma-geo-nostd" }
