[workspace]
resolver = "2"
members = ["chton"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
tagma-core = { git = "https://github.com/ssccsorg/syntagma", branch = "main" }
tagma-geo = { git = "https://github.com/ssccsorg/syntagma", branch = "main" }
tagma-kv = { git = "https://github.com/ssccsorg/syntagma", branch = "main" }
